#!/usr/bin/env bash

if [[ $# != 2 ]]; then
	echo
	echo "ln2by:  creates a reference" 
	echo "   - TO something existing      (1st arg),"
	echo "   - BY a newly created symlink (2nd arg)."
	echo
	echo "Example:"
	echo
	echo ">ln2by  /foo/bar/my_old_directory/  my_new_shortcut"
	echo
	echo
	echo "[v1.0.0   Oct 2021   github.com/umlet/ln2by   Martin Auer]"
	exit 1
fi


THE_EXISTING_THING=$1
A_NEW_SYMLINK_TO_THE_EXISTING_THING=$2


eecho() { echo "$*" 1>&2; }

if [[ -L ${A_NEW_SYMLINK_TO_THE_EXISTING_THING} ]]; then
	eecho "ERROR: symlink '${A_NEW_SYMLINK_TO_THE_EXISTING_THING}' already exists; remove/unlink first."
	exit 90
fi
if [[ -d ${A_NEW_SYMLINK_TO_THE_EXISTING_THING} ]]; then
	eecho "ERROR: '${A_NEW_SYMLINK_TO_THE_EXISTING_THING}' already exists as a directory. Are you trying to use the ludicrous '(3rd form)' of 'ln'? Ts ts."
	exit 90
fi
# If 2nd argument is an existing file, 'ln' already catches the problem.


ln -s ${THE_EXISTING_THING} ${A_NEW_SYMLINK_TO_THE_EXISTING_THING}
